apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: bindplane-gsa@principal-bird-479516-f2.iam.gserviceaccount.com
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"gateway-collectors"},"name":"gateway-collectors","namespace":"bdot-gateway"}}
  creationTimestamp: "2026-03-29T01:01:23Z"
  labels:
    app.kubernetes.io/name: gateway-collectors
  name: gateway-collectors
  namespace: bdot-gateway
  resourceVersion: "1775040790803119019"
  uid: fee55864-e58e-457e-b1c9-330f2b05a532
