apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability-platform
  namespace: argocd
spec:
  description: Observability Platform
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

